### PR TITLE
Fixed readme formatting

### PR DESCRIPTION
**Pull request by Kenny2github**
This is just a small fix to README.md - the formatting was broken. I’ve made it a proper heading now.

### CODE REVIEW

**Comment by 439bananas** [comment]
No - I don't see any change.

**Comment by Kenny2github** [comment]
You can see the change if you compare the branches - look closely

**Comment by 439bananas** [comment]
wait, how do you compare them

**Review by 439bananas — APPROVED** [review]
Ah, I see.

**Pull request merged**
